service: stock-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  stock:
    handler: handler.handler
    events:
      - sqs: arn:aws:sqs:ap-northeast-2:824317260845:stock_queue

plugins:
  - serverless-dotenv-plugin       
    
