service: sales-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  api:
    handler: handler.handler
    environment:
      HOSTNAME: "poject3-db.cpajpop7ewnt.ap-northeast-2.rds.amazonaws.com"
      USERNAME: "xgro"
      PASSWORD: "xgro"
      DATABASE: "xgro-DB"
      TOPIC_ARN: "arn:aws:sns:ap-northeast-2:824317260845:stock_empty"
    events:
      - httpApi: '*'

plugins:
  - serverless-ignore
